packages:
  - "apps/sdkwork-browser-common"
  - "apps/sdkwork-browser-common/packages/*"
  - "apps/sdkwork-browser-flutter-mobile"
  - "apps/sdkwork-browser-flutter-mobile/packages/*"
  - "apps/sdkwork-browser-h5"
  - "apps/sdkwork-browser-h5/packages/*"
  - "apps/sdkwork-browser-pc"
  - "apps/sdkwork-browser-pc/packages/*"
  - "../sdkwork-sdk-commons/sdkwork-sdk-common-typescript"
  - "sdks/*"
  - "sdks/sdkwork-browser-app-sdk/sdkwork-browser-app-sdk-typescript/generated/server-openapi"
  - "sdks/sdkwork-browser-backend-sdk/sdkwork-browser-backend-sdk-typescript/generated/server-openapi"
